pippeline{

    agent any
    
    options {
        ansiColor('xterm')
    }

    stages{

        stage('Building'){
            
            steps{
                 echo "Building the application"
            }
        }

        stage("API Testing"){

            steps{
                script{
                git url: "https://github.com/henriquelh1/Wooga.git"
                sh: "npm install"
                sh: "nmp update"
                sh: "docker pull swaggerapi/petstore"
                sh: "docker run -d -e SWAGGER_HOST=http://petstore.swagger.io \ -e SWAGGER_URL=http://localhost \ -e SWAGGER_BASE_PATH=/v2 -p 80:8080 swaggerapi/petstore"
                sh:"npx cypress run"
                }
            }
        }
        
        stage("Deploying"){

            steps{
                echo "Deploying the application"
            }
        }
    }

    post {

     publishHTML([allowMissing: false, 
                alwaysLinkToLastBuild: true, 
                keepAll: false, 
                reportDir: 'cypress/results', 
                reportFiles: 'mochawesome.html', 
                reportName: 'HTML Report', 
                reportTitles: ''])
    }

}